language: java
dist: trusty
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk8
      after_success:
        - test $TRAVIS_BRANCH = "main" && test $TRAVIS_PULL_REQUEST = "false" &&
          openssl aes-256-cbc -K $encrypted_86201c680fbc_key -iv $encrypted_86201c680fbc_iv -in keys.gpg.enc -out keys.gpg -d &&
          gpg --import keys.gpg &&
          ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Durlcheck.disabled=true -Dmaven.test.skip=true
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: linux
      jdk: openjdk-ea
script: 
  - ./mvnw clean package -Dmaven.javadoc.skip=false

